name = haunteds_foods
description = More types of meals, drinks and ingredients. Most items don't have a recipe without farming redo installed.
depends = default, farming, vessels
optional_depends = animalia, animalworld, mobs, df_farming, ebiomes, vegan_food
author = Haunted
title = Haunted's Foods