name = haunteds_foods
description = More types of meals and ingredients.
depends = default, farming, vessels
optional_depends = animalia, animalworld, mobs, df_farming, ebiomes, vegan_food
author = Haunted
title = Haunted's Foods